include: package:lint/analysis_options.yaml

linter:
  rules:
    # DiffAnimatedTransitionFunc requires unnamed bool parameter for usability
    avoid_positional_boolean_parameters: false
    avoid_print: false