name: diff
description: A starting point for Dart libraries or applications.
# version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  lint: ^1.1.1
  test: ^1.6.0
